// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJhjRHHFR_FuTfLVP9w8BhS4QmFPabRrk',
    appId: '1:303372657805:web:3db927806b12d17e3aeec4',
    messagingSenderId: '303372657805',
    projectId: 'chatappflutter-d1adb',
    authDomain: 'chatappflutter-d1adb.firebaseapp.com',
    storageBucket: 'chatappflutter-d1adb.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgfjBHV8qEbb3bhkTpYhtrNrKHfdl3GY8',
    appId: '1:303372657805:android:e1a92b15e224cda93aeec4',
    messagingSenderId: '303372657805',
    projectId: 'chatappflutter-d1adb',
    storageBucket: 'chatappflutter-d1adb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzrple549-pHVtf8UBbOxMRZrmqLDf3lo',
    appId: '1:303372657805:ios:6f24bfd50c6bd1953aeec4',
    messagingSenderId: '303372657805',
    projectId: 'chatappflutter-d1adb',
    storageBucket: 'chatappflutter-d1adb.firebasestorage.app',
    iosBundleId: 'com.amanthakur.chatapp.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzrple549-pHVtf8UBbOxMRZrmqLDf3lo',
    appId: '1:303372657805:ios:6f24bfd50c6bd1953aeec4',
    messagingSenderId: '303372657805',
    projectId: 'chatappflutter-d1adb',
    storageBucket: 'chatappflutter-d1adb.firebasestorage.app',
    iosBundleId: 'com.amanthakur.chatapp.chatapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJhjRHHFR_FuTfLVP9w8BhS4QmFPabRrk',
    appId: '1:303372657805:web:c5f6d271431055313aeec4',
    messagingSenderId: '303372657805',
    projectId: 'chatappflutter-d1adb',
    authDomain: 'chatappflutter-d1adb.firebaseapp.com',
    storageBucket: 'chatappflutter-d1adb.firebasestorage.app',
  );
}
